@hostname = localhost
#@hostname = 192.168.30.10
@port = 3000

########### Send request to /config RpiGPIOServer de dev ou de prod
### Demande d'execution de la fonction "testbutton" sur RpiGPIOServer
POST http://{{hostname}}:{{port}}/config
content-type: application/json

{
    "FctName": "testbutton",
    "FctData": {"name": "Button-1"}
}

### Demande d'execution de la fonction "login" sur RpiGPIOServer
POST http://{{hostname}}:{{port}}/config
content-type: application/json

{
    "FctName": "login",
    "FctData": {"login":"Aquagreen", "pass": "123"}
}

### Demande d'execution de la fonction "pingworker" sur RpiGPIOServer
POST http://{{hostname}}:{{port}}/config
content-type: application/json

{
    "FctName": "pingworker",
    "FctData": ""
}

### Demande d'execution de la fonction "getworkerconfig" sur RpiGPIOServer
POST http://{{hostname}}:{{port}}/config
content-type: application/json

{
    "FctName": "getworkerconfig",
    "FctData": ""
}

########### Send request to /API RpiGPIOServer de dev ou de prod
########### simule une demande envoyée par Aquagreen server
### Aquagreen send "ping" et RpiGPIOServer respond with pong
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "ping",
    "FctData": ""
}

### Aquagreen send "getconfig" et RpiGPIOServer respond with config
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "getconfig",
    "FctData": ""
}

### Aquagreen send "setconfig"
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "setconfig",
    "FctData": {"config":[{
        "pin": "2",
        "type": "Relais",
        "name": "Relais1",
        "status": "high",
        "activelow": "true",
        "timeout": "9",
        "custom": {
                "displayname": "Garage",
                "relaistype": "Turbine"
            }
      }]}
}

### Aquagreen send "setgpio"
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "setgpio",
    "FctData": {"name": "Relais 1", "value": 0}
}

### Aquagreen send "getgpio"
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "getgpio",
    "FctData": {"name": "Relais 1"}
}

### Aquagreen send "getstatus"
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "getstatus",
    "FctData": ""
}

### Aquagreen send "ApiRestart" et RpiGPIOServer fait un restart
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "restart",
    "FctData": ""
}