#@hostname = localhost
@hostname = 192.168.30.10
@port = 3000

### testbutton
POST http://{{hostname}}:{{port}}/config
content-type: application/json

{
    "FctName": "testbutton",
    "FctData": "{\"name\": \"Button1\"}"
}

### login
POST http://{{hostname}}:{{port}}/config
content-type: application/json

{
    "FctName": "login",
    "FctData": "{\"login\": \"Aquagreen\", \"pass\": \"123\"}"
}

### pingworker
POST http://{{hostname}}:{{port}}/config
content-type: application/json

{
    "FctName": "pingworker",
    "FctData": ""
}

### getworkerconfig
POST http://{{hostname}}:{{port}}/config
content-type: application/json

{
    "FctName": "getworkerconfig",
    "FctData": ""
}

########### API
### Ping 
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "ping",
    "FctData": ""
}

### getconfig
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "getconfig",
    "FctData": ""
}

### setconfig
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "setconfig",
    "FctData": "{\"config\": [{\"pin\":2, \"type\": \"Relais\", \"name\": \"Relais1\", \"statu\": \"high\", \"activeLow\" : true, \"TimeOut\": 10},{\"pin\":3, \"type\": \"Relais\", \"name\": \"Relais2\", \"statu\": \"high\", \"activeLow\" : true, \"TimeOut\": 10},{\"pin\":7, \"type\": \"Button\", \"name\": \"Button1\", \"statu\": \"rising\", \"debounceTimeout\" : 500}]}"
}

### setgpio
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "setgpio",
    "FctData": "{\"name\": \"Relais1\", \"value\": 1}"
}

### getgpio
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "getgpio",
    "FctData": "{\"name\": \"Relais1\"}"
}

### getstatus
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "getstatus",
    "FctData": ""
}

### ApiRestart
POST http://{{hostname}}:{{port}}/api
content-type: application/json

{
    "FctName": "restart",
    "FctData": ""
}